site_name: cython-extensions
theme:
  name: material
  favicon: assets/favicon.ico
  palette:
  - scheme: default
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  default_palette_scheme: slate
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github-alt
  language: en

nav:
  - Cython Extensions SC2: index.md

repo_name: cython-extensions-sc2
repo_url: https://github.com/AresSC2/cython-extensions-sc2

# to navigate with `/site` content correctly
use_directory_urls: false

plugins:
  - search
  - mkdocstrings:
      watch: [cython_extensions]
      handlers:
        python:
          paths: [cython_extensions]
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: false
            show_root_full_path: false
            heading_level: 2
            merge_init_into_class: true
            show_signature_annotations: false
            separate_signature: true
            show_root_toc_entry: false

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
